### ISSUE TITLE
 Automatically update python packages during `trellis init`

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis-cli#102]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Automatically update python packages during `trellis init`.

## Motivation

Update dependencies when [`requirements.txt`](https://github.com/roots/trellis/blob/ac87cd5af42ea8194499606119b610db265ec501/requirements.txt) is changed OR newer versions of python packages available.

Same motivation as https://github.com/roots/trellis-cli/issues/95#issuecomment-576044178

**Comment by swalkinshaw** [comment]
I think this is different from the Galaxy issue mostly because ansible-galaxy isn't very good 🙈 

With galaxy if you change a version number it wouldn't update it (or you'd have to force update everything). With pip it works as you'd expect.

1. run `pip install -r requirements.txt`
2. bump a version number
3. run `pip install -r requirements.txt` again and it will update that package

`pip install -r requirements.txt --upgrade` exists to packages within a version *range* but that's a bit different and mirrors every other package/dependency manager.

So I'm inclined to just delegate this responsible to pip

**Comment by TangRufus** [comment]
Dont we want to make `trellis init` idempotent?

### Example of non-idempotent

```sh-session
$ cat requirements.txt
ansible>=2.7.12,<2.9
passlib
```

Assume ansible v2.8.0 is the latest version.

```sh-session
$ trellis init
$ trellis exec ansible --version
ansible 2.8.0
```

Then, ansible v2.8.1 is released. `trellis init` doesn't update ansible because v2.8.0 is _in range_.

```sh-session
$ trellis init
$ trellis exec ansible --version
ansible 2.8.0
```

However, if another developer clones the repo and run `trellis init`, he will install v2.8.1 because v2.8.1 is the latest and _in range_.

**Comment by swalkinshaw** [comment]
That's because `Pip` also kind of sucks in other ways and doesn't have a lock file 😞 With most package managers this would also be solved thanks to that.

So I'd love to have the behaviour you described but we shouldn't be re-inventing pip. We could look into using another package manager like poet or pipenv but pip is great because it's easy to install and is integrated into Python 3

**Comment by swalkinshaw** [comment]
Thought about this and https://github.com/roots/trellis-cli/pull/104 a bit more.

`trellis init` already isn't idempotent as you brought up. But the proposal to run `--upgrade` doesn't make it idempotent either; though it likely makes the installed packages a bit more consistent across developers' machines.

I think #104 makes sense in the context of the `init` command being meant to *initialize an existing project* which is a one time thing. I forget your use case... but if you use `trellis init` often for things like 1) activating venv and 2) updating packages then maybe we should come up with more commands to handle that.

**Comment by TangRufus** [comment]
How about:
1. alias (or rename) `trellis init` to `trellis venv init`
    * no change to the existing init command
    * do nothing if existing venv is in range
    * non-idempotent
1. add `trellis venv upgrade`
    * run `trellis venv init` with `--upgrade`
    * always install latest _in range_ packages
    * non-idempotent; similar to `composer update`

Goal is to allow CI servers to always use the latest _in range_ ansible version and allow CI servers to cache virtuial env (`.trellis`)

Use case:
1. restore `.trellis` from cache
2. `trellis venv upgrade` <-- make sure the latest _in range_ ansible version is installed
3. save `.trellis` to cache
4. deploy


Looks like we don't have good solution to make it idempotent.

**Comment by swalkinshaw** [comment]
Isn't `trellis venv upgrade` just a shortcut for `trellis init && pip install --upgrade` which can be done now?

**Comment by swalkinshaw** [comment]
Semi-related but since the Virtualenv integration I've wanted automatic shell integration for venv activation. I have a local branch with it mostly working.

1. add `eval "$(trellis-cli shell-init zsh)"` to your shell RC file (will eventually support Bash, Zsh, and Fish)
2. `cd`ing into *any* directory within a Trellis project will auto activate the venv (if available)
3. `cd`ing out of a project will deactivate it

**Comment by swalkinshaw** [comment]
@TangRufus what do you think about this (and https://github.com/roots/trellis-cli/pull/104) now that the auto venv activation in https://github.com/roots/trellis-cli/pull/114 exists?

**Comment by TangRufus** [comment]
Question: How to upgrade `pip` in `virtualenv`?

```
$ trellis exec pip install -r requirements.txt
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/Users/rufus/Code/typist/trellis/.trellis/virtualenv/bin/python3 -m pip install --upgrade pip' command.

**Comment by swalkinshaw** [comment]
Did you try running that? Just `python3 -m pip install --upgrade pip` should work if you have the venv auto activation on too.
