### ISSUE TITLE
Allow specifying digital ocean image

### ISSUE THREAD

**Issue by robrecord** [roots/trellis-cli#161]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Allow specifying which image to use when creating digital ocean droplet, as with `doctl` command, such as `--image ubuntu-20-04-x64`

## Motivation

Local development image (vagrant) is now Ubuntu 20-04-x64; I would like my remote server to be the same

## Additional context

Perhaps the value, by default, could be taken from/somehow linked to a value in trellis
- eg. where this is already being used to specify the vagrant box to spin up in development, like `vagrant.default.yml`
- or held elsewhere in a config file such as `wordpress_sites.yml`

**Comment by swalkinshaw** [comment]
Oh wow. I completely missed the fact that we hardcoded 18.04 🤦‍♂️  here: https://github.com/roots/trellis-cli/blob/83f6de5c1303ec8c4ff1f527e275c1223b6ba148/digitalocean/main.go#L33

Is this something you want to try and contribute? It shouldn't be too difficult since it mirror other CLI options we pass down. If not, I can take a look soon.

**Comment by swalkinshaw** [comment]
https://github.com/roots/trellis-cli/pull/162

**Comment by robrecord** [comment]
@swalkinshaw thanks for the invitation to contribute. I would like to do this some day!
