### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by swalkinshaw** [roots/trellis-cli#26]
We need some windows users to test trellis-cli.

@kalenjohnson or @QWp6t? 😄

**Comment by pachiraDIG** [comment]
I'm up for it. I just started using the roots stack and haven't had experience with deployments quite yet, but I can accurately provide results.

**Comment by swalkinshaw** [comment]
Anyone is welcome to test so thank you :thumbsup:

Although the same rules with Trellis itself apply to trellis-cli for Windows users: most of the commands need to be run where Ansible is installed. So that's either *on* the Vagrant VM or WSL I guess if that works.

**Comment by pachiraDIG** [comment]
Though I have Absible installed in both environments, I'll try on the VM
first. Probably the more stable approach.

Will give it a shot next week. Have a great weekend!

**Comment by swalkinshaw** [comment]
`trellis new` should be expected to work on Windows though (even native Windows outside of WSL).

**Comment by mmirus** [comment]
Initial testing on WSL...

I first tried to Install Trellis in WSL with: `brew install roots/tap/trellis-cli`. It successfully installed, though I had to add execute permissions to the binary before I could run it. When I was able to run it, however, I got this error: `exec format error: trellis`. Pretty sure this is because brew installed the Darwin version of the package. I tried using `--build-from-source`, but that didn't seem to change anything; still used Darwin.

Uninstalled the Homebrew version and instead grabbed the latest Linux_x86_64 release from this repo and dropped it into a location in my WSL user's path (`~/bin` in my case).

So far so good after that, but haven't tested much:

1. `trellis check` didn't find Vagrant or VirtualBox, both of which I have installed in Windows, not WSL, though they are available as commands in WSL.
2. `trellis new` successfully created a new project, which I was able to `vagrant up` and browse around without problem.

Nice job!

**Comment by swalkinshaw** [comment]
@mmirus 

> 1. didn't find Vagrant or VirtualBox, both of which I have installed in Windows, not WSL, though they are available as commands in WSL.

Just to confirm, `vagrant` and `VBoxManage` commands exist/work on WSL?

**Comment by mmirus** [comment]
@swalkinshaw I was 50% correct. `vagrant` is aliased in WSL:

![image](https://user-images.githubusercontent.com/524994/52714899-12809900-2f69-11e9-96e8-c137d2544d1e.png)

But the CLI was correct about VirtualBox, which is just accessible to Vagrant (which runs on the Windows side, even though it's invoked from within WSL). VirtualBox is not set up be accessible within WSL itself, since it doesn't need to be for Vagrant to use it. I could probably add an alias for it, though!

Also, I forgot to mention that `trellis info` works too, but prints the same domain (`trellis-cli-test.com` in this case) for all three environments. Am I correct that it should print `trellis-cli-test.test` for the development environment, since that's what's defined in the dev `wordpress_sites.yml`?

**Comment by swalkinshaw** [comment]
> Am I correct that it should print `trellis-cli-test.test` for the development environment, since that's what's defined in the dev `wordpress_sites.yml`?

🤔 there was a bug which was fixed in a previous version. You have the latest one?

**Comment by mmirus** [comment]
Hm... I downloaded trellis_0.3.0_Linux_x86_64.tar.gz from the releases page, but when I run `trellis -v` I get 0.2.1. Wrong version bundled up for the release, maybe?

**Comment by swalkinshaw** [comment]
That's just my fault since I forget to bump the number in code 😞 

But 0.3.1 may have the `info` fix, I forget.

**Comment by mmirus** [comment]
I can retest it once you put up 0.3.1. Anything else you want me to check?

**Comment by swalkinshaw** [comment]
Ah sorry I was confused. `0.3.0` is the latest, the `version` returned is just wrong. Anyway the fix I was talking about was in `0.2.0`: https://github.com/roots/trellis-cli/commit/61c3becaa83ec82c1ccf0c08eada86500ba0bcbe

So maybe this is something else

**Comment by mmirus** [comment]
`trellis info` is working correctly; it was a misunderstanding on my part. It returns the name of the site from `wordpress_sites.yml`, not the canonical domain, which I was expecting.

**Comment by alwaysblank** [comment]
Running v0.3.1 in actual Windows (not WSL) does nothing: The executable runs, but doesn't appear to do anything and provides no feedback of any kind. I can see it running in Task Manager, but all it does is gradually use up more and more ran (been running for a few minutes and it's up to about 230MB). All commands I've tested (i.e. `trellis new`) produce the same result. I'm on Windows 10.

**Comment by retlehs** [comment]
i believe the plan is to only support windows via WSL

**Comment by alwaysblank** [comment]
That's understandable, but it seems odd to provide an Windows .exe in releases if Windows isn't supported. @swalkinshaw also says earlier in this thread that it should run in "normal" Windows: https://github.com/roots/trellis-cli/issues/26#issuecomment-462157261

**Comment by swalkinshaw** [comment]
Ideally it should, but I can't test myself which makes it hard 😛. I wonder how we could debug that 🤔

**Comment by QWp6t** [comment]
I'm off to a good start, but I had to alias VBoxManage to VBoxManage.exe, so maybe trellis-cli should look for VBoxManage.exe? 🤷‍♂️

![image](https://user-images.githubusercontent.com/2104321/73629191-2ce2d500-4607-11ea-9a97-2b4319ce4406.png)

**Comment by swalkinshaw** [comment]
🤔 true. There's a few assumptions made like that:

* vagrant (shouldn't that be vagrant.exe too?)
* VBoxManage
* Python

I'd at least like trellis-cli to work on WSL properly for one thing. Then natively on Windows would be another goal.

**Comment by QWp6t** [comment]
vagrant and python are both installed within WSL, so you don't need to reference them externally in windows as .exe files (_especially_ python, since the reason we use python is for ansible, and ansible doesn't run in Windows, but it does run in WSL). VirtualBox cannot install in WSL, so VBoxManage.exe has to be called to access the Windows version of it.

**Comment by QWp6t** [comment]
Somewhat relevant: nfs is probably going to be an issue. Windows users can typically use winnfsd, but when you run vagrant from wsl, it won't use winnfsd. wsl 2.0 supports nfs natively, but i don't know if that even matters since vagrant doesn't actually check if nfs is supported; on windows, vagrant hard-codes that nfs isn't supported. (cf. [linux/cap/nfs.rb](https://github.com/hashicorp/vagrant/blob/master/plugins/hosts/linux/cap/nfs.rb) vs [windows/cap/nfs.rb](https://github.com/hashicorp/vagrant/blob/master/plugins/hosts/windows/cap/nfs.rb)).

the reason this matters for us is that basically every other mount type is so slow that it's unusable for our purposes.

**Comment by swalkinshaw** [comment]
Closing this since we assume trellis-cli works on Windows via WSL unless people tell us otherwise 😄
