### ISSUE TITLE
Feature Request: generate .vault_pass for existing sites

### ISSUE THREAD

**Issue by mike-sheppard** [roots/trellis-cli#300]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

`./trellis/.vault_pass` is required for the `trellis dotenv` task to run. It'd be great if the dotenv command either:

- Automatically generates `./trellis/.vault_pass` if missing during `trellis init` OR `trellis dotenv`
- Or throws an error message that informs the user to create one before running the task

### Motivation

`trellis new` creates the `./trellis/.vault_pass` but it isn't a commited file, so when a new user clones the repo/project + runs `trellis init` the vault pass is not created, leading to the error below.

### Additional Context

Current error message from `trellis dotenv` on a project without a `.vault_pass` file
<img width="1060" alt="trellis dotenv error" src="https://user-images.githubusercontent.com/1690006/170457629-5c2ac58c-77f8-4163-a4b2-f8418d091b5a.png">

**Comment by swalkinshaw** [comment]
Sorry for the delay @mike-sheppard and thanks for the good issue!

@TangRufus had started looking into this in #302 and then I was starting to prioritize fixing this after [another report](https://discourse.roots.io/t/trellis-dotenv-exit-status-1/23875/4). I went down a similar path as @TangRufus to try to validate that a Vault pass file existed.

However, a `.vault_pass` isn't actually _required_. It's only required if the files are already encrypted. In those cases, generating a new password file isn't correct since you'd need the original password that was used to encrypt them.

Example:
1. developer A creates a project + pushes it git
2. developer B clones repo, runs `trellis dotenv`
3. 💣 fails because B is missing `.vault_pass`

The solution is for B to get the password from A and create that file locally.

So ultimately I think the best solution is to just output the proper error message which will point anyone in the right direction:

```plain
trellis dotenv
[✘] Error templating .env file
[WARNING]: Error getting vault password file (default): The vault password file
/Users/scottwalkinshaw/dev/trellis/.vault_pass was not found
ERROR! The vault password file /Users/scottwalkinshaw/dev/trellis/.vault_pass was not found
```

https://github.com/roots/trellis-cli/pull/319 will do this and also fixes the hidden error output in a few other commands.

**Comment by mike-sheppard** [comment]
Yup sounds good! + that error msg is perfect 👍🏻
