### ISSUE TITLE
`.vault_pass` file and `vault_password_file` config setting missing on existing projects

### ISSUE THREAD

**Issue by devotoare** [roots/trellis-cli#478]
### Version

1.12.1

### What did you expect to happen?

Generate a `.vault_pass` file as per the [docs](https://roots.io/trellis/docs/vault/).

For context I'm running this in the `trellis` and root folders of a new radicle project. Even if I manually create the `trellis/.vault_pass` file here it's not being recognized and I can't do anything, including deploy. So this may be a setup problem, but I would still expect the file to be created.

### What actually happens?

It did not generate a file.

### Steps to reproduce

`trellis vault encrypt`

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Thanks for the report! This behavior will be fixed for Radicle when it switches to use `trellis new` (https://github.com/roots/radicle/issues/99)

Since you're manually creating `.vault_pass`, open up `ansible.cfg` and add this line:

```yaml
vault_password_file = .vault_pass
```

You should be good once that's in place. I'll get our docs updated with this as well — they previously had that instruction, but we removed it once `trellis new` handled adding that line automatically

**Comment by devotoare** [comment]
Confirmed fix works as expected, thank you!
