### ISSUE TITLE
Log command

### ISSUE THREAD

**Issue by retlehs** [roots/trellis-cli#5]
`trellis log` could be used to access the error and access logs from all environments

**Comment by codepuncher** [comment]
Was just about to create a new issue for this as I found myself wanting this feature.

Is there a recommended approach to get going with writing this feature?

**Comment by swalkinshaw** [comment]
The simplest possible implementation here would be to run `ssh user@server "tail -f /srv/www/site/logs/*"` to output all logs. There could be flags for access/errors only.

We could potentially leverage the existing `ssh` command (or extract parts into a common function). One issue is that `trellis ssh` isn't great since it's tied to the WP site and uses the host/IP from the site, not the `hosts` file.
